version: '2'
volumes: 
    home:
services:
  code-server:
    #image: codercom/code-server:latest
    build: .
    privileged: true
    ports:
      - "80:8080"
    volumes: 
      - 'home:/home/coder'
